name: Node.js Package
on:
  release:
    types: [created]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.4
    # Setup .npmrc file to publish to npm
    - uses: actions/setup-node@v2.1.5
      with:
        node-version: '14.x'
        registry-url: 'https://registry.npmjs.org'
    - run: yarn --frozen-lockfile
    - run: yarn publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
